# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Build API Data

# Define os gatilhos que iniciam a automação
on:
  # Gatilho 1: Executa quando há um push para a branch 'main'
  push:
    branches: [ "main" ]
  
  # Gatilho 2: Executa em um horário agendado (ex: toda segunda-feira às 02:00)
  schedule:
    - cron: '0 2 * * 1'

  # Permite executar este workflow manualmente a partir da aba "Actions"
  workflow_dispatch:

# Define as tarefas a serem executadas
jobs:
  build:
    runs-on: ubuntu-latest # Usa um ambiente Linux para executar os comandos
    
    steps:
      # Passo 1: Baixa o código do seu repositório para o ambiente da Action
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instala as dependências listadas no requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # Passo 4: Executa o seu script de construção da API
      - name: Run build script
        run: python build_api.py

      # Passo 5: Verifica se houve alterações na pasta 'docs' e faz o commit/push
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # --- ALTERAÇÃO AQUI: Adiciona a flag -f para forçar a adição da pasta ignorada ---
          git add -f docs/
          # O comando a seguir verifica se há ficheiros preparados para commit
          # Se houver, ele faz o commit e o push. Se não, não faz nada.
          git diff --staged --quiet || (git commit -m "Automated build: Update API data" && git push)
