# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Build and Deploy API

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Passo 1: Baixa o código do seu repositório (excluindo a pasta /docs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Configura o ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Passo 3: Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      # Passo 4: Executa o seu script para gerar a pasta /docs
      - name: Run build script
        run: python build_api.py

      # Passo 5: Faz o deploy da pasta /docs para a branch gh-pages
      # Esta ação irá criar e gerir a branch gh-pages automaticamente.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # A pasta que contém o "produto final" da sua API
          publish_dir: ./docs
          # Opcional: mantém o histórico de deploys na branch gh-pages
          keep_files: false
